export { ReactComponent as ChatIcon } from './chat.svg'
export { ReactComponent as BurgerIcon } from './burger-icon.svg'
export { ReactComponent as ClockIcon } from './clock.svg'
export { ReactComponent as CameraIcon } from './camera.svg'
export { ReactComponent as UserIcon } from './user.svg'
export { ReactComponent as GraphIcon } from './graph.svg'
export { ReactComponent as PlusIcon } from './plus.svg'
export { ReactComponent as BoldPlusIcon } from './plus-bold.svg'
export { ReactComponent as UpIcon } from './up.svg'
export { ReactComponent as PlayArrowIcon } from './play-arrow.svg'
export { ReactComponent as AvatarPlaceholderIcon } from './avatar.svg'
export { ReactComponent as EditIcon } from './edit.svg'
export { ReactComponent as TrashIcon } from './trash.svg'
export { ReactComponent as LinkIcon } from './link.svg'
export { ReactComponent as NotificationBellIcon } from './notification-bell.svg'
export { ReactComponent as NotificationBellFilledIcon } from './notification-bell-filled.svg'
export { ReactComponent as ScullWithBgIcon } from './scull-with-bg.svg'
export { ReactComponent as ScullIcon } from './scull.svg'
export { ReactComponent as DownIcon } from './down.svg'
export { ReactComponent as TickFilledIcon } from './tick.svg'
export { ReactComponent as CrossFilledIcon } from './cross.svg'
export { ReactComponent as MinusFilledIcon } from './minus-cirlce-filled.svg'
export { ReactComponent as ClockFilledIcon } from './clock-filled.svg'
export { ReactComponent as TickIcon } from './pure-tick.svg'
export { ReactComponent as CrossIcon } from './pure-cross.svg'
export { ReactComponent as ExitCrossIcon } from './exit-cross.svg'
export { ReactComponent as InfoIcon } from './info.svg'
export { ReactComponent as AtSignIcon } from './at-sign.svg'
export { ReactComponent as EmojiIcon } from './emoji.svg'
export { ReactComponent as SendPlaneIcon } from './send-plane.svg'
export { ReactComponent as DiamondIcon } from './diamond.svg'
export { ReactComponent as TimerClockIcon } from './timer-clock.svg'
export { ReactComponent as TimerIcon } from './timer.svg'
export { ReactComponent as DoorOutIcon } from './door-out.svg'
export { ReactComponent as TransactionsIcon } from './transactions.svg'
export { ReactComponent as SettingIcon } from './setting.svg'
export { ReactComponent as ChevronUpIcon } from './chevron-up.svg'
export { ReactComponent as CoinsIcon } from './coins.svg'
export { ReactComponent as ShrinkIcon } from './shrink.svg'
export { ReactComponent as ExpandIcon } from './expand.svg'
export { ReactComponent as TriangleDownIcon } from './triangle-down-rounded.svg'
export { ReactComponent as HideSidebarIcon } from './hide-sidebar.svg'
export { ReactComponent as LockIcon } from './lock.svg'
export { ReactComponent as CopyIcon } from './copy-icon.svg'
export { ReactComponent as InfoCircleIcon } from './info-circle.svg'
export { ReactComponent as PlayerIcon } from './player.svg'
export { ReactComponent as TopLeftArrowIcon } from './top-right-arrow.svg'
export { ReactComponent as ArrowUpIcon } from './up.svg'
export { ReactComponent as RoundedTickIcon } from './rounded-tick.svg'
export { ReactComponent as RoundedCrossIcon } from './rounded-cross.svg'
export { ReactComponent as WarningTriangleIcon } from './warning-triangle.svg'
export { ReactComponent as FundsUpCircleIcon } from './funds-up-circle.svg'
export { ReactComponent as JoystickIcon } from './joystick.svg'
export { ReactComponent as CupIcon } from './cup.svg'
export { ReactComponent as TickBoldIcon } from './tick-bold.svg'
export { ReactComponent as TaskLockIcon } from './task-lock.svg'
export { ReactComponent as Web3Icon } from './web3.svg'
export { ReactComponent as RefreshIcon } from './refresh.svg'
export { ReactComponent as HotIcon } from './hot.svg'
export { ReactComponent as QuestionSymbol } from './question-symbol.svg'
export { ReactComponent as NoteIcon } from './note.svg'
export { ReactComponent as StrongboxIcon } from './strongbox.svg'
export { ReactComponent as ArrowDownSingle } from './arrow-down-single.svg'

export { ReactComponent as ConnectIcon } from './connect.svg'
export { ReactComponent as VerifyBadgeIcon } from './verify-badge.svg'

export { ReactComponent as RoundedTick } from './rounded-tick.svg'
export { ReactComponent as RoundedCross } from './rounded-cross.svg'

export { default as tickBoxIconPath } from './tick-box.svg'
export { default as crossBoxIconPath } from './cross-box.svg'
export { default as alertBoxIconPath } from './alert-box.svg'
export { default as scullWithBg } from './scull-with-bg.svg'

export { ReactComponent as BoldArrowRight } from './bold-arrow-right.svg'

export {
  default as penIconPath,
  ReactComponent as PenIcon
} from './pen-icon.svg'
