export { ReactComponent as SetupsIcon } from './page-setups.svg'
export { ReactComponent as HomeIcon } from './page-home.svg'
export { ReactComponent as HomeRoundedIcon } from './home-rounded.svg'
export { ReactComponent as OneVsOneIcon } from './page-1vs1.svg'
export { ReactComponent as X1000Icon } from './page-x1000.svg'
export { ReactComponent as BullsEyeIcon } from './page-bulls-eye.svg'
export { ReactComponent as UpDownIcon } from './page-up-down.svg'

export { ReactComponent as SetupsNavIcon } from './setups.svg'
export { ReactComponent as BullsEyeNavIcon } from './bulls-eye.svg'
export { ReactComponent as HomeNavIcon } from './home.svg'
export { ReactComponent as OneVsOneNavIcon } from './1vs1.svg'
export { ReactComponent as UpDownNavIcon } from './up-down.svg'
export { ReactComponent as X1000NavIcon } from './x1000.svg'
