export { default as bannerPartAllModes } from './banner-part-all-modes.png'
export { default as bannerPartBullsEye } from './banner-part-bulls-eye.png'
export { default as bannerPartSetups } from './banner-part-setups.png'
export { default as bannerPartUpDown } from './banner-part-up-down.png'
export { default as bannerPartCreateSetups } from './banner-part-create-setups.png'
export { default as bannerPartDiscord } from './banner-part-discord.png'
export { default as bannerPartTwitter } from './banner-part-twitter.png'
export { default as bannerPartFaq } from './banner-part-faq.png'

export { default as welcomeWindowStepOneBanner } from './welcome-window-step-1-banner.png'
export { default as welcomeWindowStepTwoBanner } from './welcome-window-step-2-banner.png'
export { default as welcomeWindowStepThreeBanner } from './welcome-window-step-3-banner.png'
